use std::env;
use std::fs;
use std::path::PathBuf;

#[path = "src/supported_langs.rs"]
mod supported_langs;

#[path = "src/download_utils.rs"]
mod download_utils;

use download_utils::{download_file, get_system_info};
use supported_langs::{get_extensions_for_language, SupportedLanguage};

fn main() {
    println!("cargo:rustc-check-cfg=cfg(feature, values(\"embedded_libs\"))");

    let pre_tree_sitter_register = env::var("PRE_TREE_SITTER_REGISTER").unwrap_or_default();
    let url = std::env::var("TREE_SITTER_BASE_URL")
        .unwrap_or_else(|_| "https://tree-sitter-parsers.s3.us-east-1.amazonaws.com".to_string());
    println!("cargo:rustc-env=TREE_SITTER_BASE_URL={url}");

    if pre_tree_sitter_register.is_empty() || pre_tree_sitter_register == "false" {
        let out_dir = env::var("OUT_DIR").unwrap();
        let dest_path = PathBuf::from(&out_dir).join("embedded_libs.rs");
        let empty_code = r#"// No embedded libraries
use std::collections::HashMap;
use std::sync::OnceLock;

pub struct EmbeddedLib {
    pub data: &'static [u8],
    pub symbol: String,
    pub meta_var_char: Option<char>,
    pub expando_char: Option<char>,
    pub extensions: Vec<String>,
}

static EMBEDDED_LIBS: OnceLock<HashMap<String, EmbeddedLib>> = OnceLock::new();

pub fn get_embedded_libs() -> &'static HashMap<String, EmbeddedLib> {
    EMBEDDED_LIBS.get_or_init(HashMap::new)
}
"#;
        fs::write(&dest_path, empty_code).expect("Failed to write empty embedded_libs.rs");
        return;
    }

    println!("cargo:rustc-cfg=feature = \"embedded_libs\"");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = PathBuf::from(&out_dir).join("embedded_libs.rs");

    let mut generated_code = String::from("// Auto-generated by build.rs\n");
    generated_code.push_str("use std::collections::HashMap;\n");
    generated_code.push_str("use std::sync::OnceLock;\n\n");
    generated_code.push_str("pub struct EmbeddedLib {\n");
    generated_code.push_str("    pub data: &'static [u8],\n");
    generated_code.push_str("    pub symbol: String,\n");
    generated_code.push_str("    pub meta_var_char: Option<char>,\n");
    generated_code.push_str("    pub expando_char: Option<char>,\n");
    generated_code.push_str("    pub extensions: Vec<String>,\n");
    generated_code.push_str("}\n\n");

    generated_code.push_str(
        "static EMBEDDED_LIBS: OnceLock<HashMap<String, EmbeddedLib>> = OnceLock::new();\n\n",
    );
    generated_code
        .push_str("pub fn get_embedded_libs() -> &'static HashMap<String, EmbeddedLib> {\n");
    generated_code.push_str("    EMBEDDED_LIBS.get_or_init(|| {\n");
    generated_code.push_str("        let mut map = HashMap::new();\n");

    let languages = SupportedLanguage::all_langs();

    let (os, arch, extension) = get_system_info();

    // Create a tokio runtime for async downloads
    let rt = tokio::runtime::Runtime::new().expect("Failed to create tokio runtime");

    for language in languages {
        let lang_name = language.to_string();
        let extensions = get_extensions_for_language(language);

        // Build the download URL
        let final_url = format!(
            "{url}/tree-sitter/parsers/tree-sitter-{lang_name}/latest/{os}-{arch}.{extension}"
        );

        // Build the library path for caching in tmp directory
        let lib_path = env::temp_dir()
            .join("codemod_tree_sitter_libs")
            .join(&lang_name)
            .join(format!("{os}-{arch}.{extension}"));

        // Download the file if it doesn't exist
        if !lib_path.exists() {
            println!("Downloading tree-sitter parser for {lang_name}...");
            if let Err(e) = rt.block_on(async { download_file(&final_url, &lib_path, None).await })
            {
                panic!("Failed to download tree-sitter parser for {lang_name}: {e}");
            }
        }

        // Generate a safe variable name
        let var_name = lang_name
            .replace('-', "_")
            .replace('+', "plus")
            .to_uppercase();
        let bytes_var = format!("{}_BYTES", var_name);

        // Add include_bytes! for this library
        generated_code.push_str(&format!(
            "        const {}: &[u8] = include_bytes!(\"{}\");\n",
            bytes_var,
            lib_path.to_string_lossy().replace('\\', "\\\\")
        ));

        // Generate the symbol name
        let symbol = format!("tree_sitter_{}", lang_name.replace('-', "_"));

        // Add to map
        generated_code.push_str(&format!(
            "        map.insert(\"{}\".to_string(), EmbeddedLib {{\n",
            lang_name
        ));
        generated_code.push_str(&format!("            data: {},\n", bytes_var));
        generated_code.push_str(&format!(
            "            symbol: \"{}\".to_string(),\n",
            symbol
        ));
        generated_code.push_str("            meta_var_char: Some('$'),\n");
        generated_code.push_str("            expando_char: Some('$'),\n");
        generated_code.push_str(&format!(
            "            extensions: vec![{}],\n",
            extensions
                .iter()
                .map(|s| format!("\"{}\".to_string()", s))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        generated_code.push_str("        });\n");

        println!("cargo:rerun-if-changed={}", lib_path.display());
    }

    generated_code.push_str("        map\n");
    generated_code.push_str("    })\n");
    generated_code.push_str("}\n");

    // Write the generated code
    fs::write(&dest_path, &generated_code).expect("Failed to write generated code");

    println!("cargo:rerun-if-env-changed=PRE_REGISTER_JSON_CONFIG");
}
