version: "1"

params:
  language: "{language}"
  run_shell: true
  run_yaml: true
  run_jssg: true

nodes:
  - id: shell-setup
    name: Setup (shell)
    type: automatic
    steps:
      - name: "Setup"
        run: ./scripts/setup.sh

  - id: shell-transform
    name: Transform (shell)
    type: automatic
    depends_on: [shell-setup]
    steps:
      - name: "Transform"
        run: ./scripts/transform.sh

  - id: apply-yaml
    name: Apply YAML ast-grep rules
    type: automatic
    depends_on: [shell-transform]
    steps:
      - name: "Scan {language} files with YAML rules"
        ast-grep:
          config_file: "rules/config.yml"

  - id: jssg-apply
    name: Apply JS ast-grep transform
    type: automatic
    depends_on: [apply-yaml]
    steps:
      - name: "Scan {language} files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "{language}"

  - id: shell-cleanup
    name: Cleanup (shell)
    type: automatic
    depends_on: [jssg-apply]
    steps:
      - name: "Cleanup"
        run: ./scripts/cleanup.sh
