# Convert snake_case JSON keys to camelCase
# This helps modernize API responses and configuration files
id: snake-case-to-camel-case
language: json
rule:
  kind: string
  inside:
    kind: pair
    field: key
  regex: "^\"[a-z][a-z0-9]*(_[a-z0-9]+)+\"$"
transform:
  CAMEL_CASE:
    convert:
      toCase: camelCase
      source: $0
      # Remove quotes and underscores, then convert
      replace: "^\"(.*)\"$"
      by: $1
fix: '"$CAMEL_CASE"'
