# Modernize Docker Compose v2 to v3 format
# This helps update legacy Docker Compose configurations
id: docker-compose-v2-to-v3
language: yaml
rule:
  kind: block_mapping_pair
  has:
    field: key
    kind: plain_scalar
    regex: ^version$
  has:
    field: value
    kind: plain_scalar
    regex: ^['"]?2(\.\d+)?['"]?$
fix: |
  version: '3.8'
---
# Remove deprecated links configuration
id: remove-docker-compose-links
language: yaml  
rule:
  kind: block_mapping_pair
  has:
    field: key
    kind: plain_scalar
    regex: ^links$
  inside:
    kind: block_mapping_pair
    inside:
      kind: block_mapping_pair
      has:
        field: key
        kind: plain_scalar
        regex: ^services$
fix: |
  # links removed - use networks instead
  networks:
    - default
