use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rustc-check-cfg=cfg(embedded_libs)");

    let pre_register_config = env::var("PRE_REGISTER_JSON_CONFIG").unwrap_or_default();

    if pre_register_config.is_empty() {
        let out_dir = env::var("OUT_DIR").unwrap();
        let dest_path = PathBuf::from(&out_dir).join("embedded_libs.rs");
        let empty_code = r#"// Auto-generated by build.rs - No embedded libraries
use std::collections::HashMap;
use std::sync::OnceLock;

pub struct EmbeddedLib {
    pub data: &'static [u8],
    pub symbol: String,
    pub meta_var_char: Option<char>,
    pub expando_char: Option<char>,
    pub extensions: Vec<String>,
}

static EMBEDDED_LIBS: OnceLock<HashMap<String, EmbeddedLib>> = OnceLock::new();

pub fn get_embedded_libs() -> &'static HashMap<String, EmbeddedLib> {
    EMBEDDED_LIBS.get_or_init(|| HashMap::new())
}
"#;
        fs::write(&dest_path, empty_code).expect("Failed to write empty embedded_libs.rs");
        return;
    }

    println!("cargo:rustc-cfg=embedded_libs");

    let json_content = if PathBuf::from(&pre_register_config).exists() {
        println!("cargo:rerun-if-changed={}", pre_register_config);
        fs::read_to_string(&pre_register_config)
            .expect("Failed to read PRE_REGISTER_JSON_CONFIG file")
    } else {
        pre_register_config
    };

    let config: HashMap<String, serde_json::Value> =
        serde_json::from_str(&json_content).expect("Failed to parse PRE_REGISTER_JSON_CONFIG");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = PathBuf::from(&out_dir).join("embedded_libs.rs");

    let mut generated_code = String::from("// Auto-generated by build.rs\n");
    generated_code.push_str("use std::collections::HashMap;\n");
    generated_code.push_str("use std::sync::OnceLock;\n\n");
    generated_code.push_str("pub struct EmbeddedLib {\n");
    generated_code.push_str("    pub data: &'static [u8],\n");
    generated_code.push_str("    pub symbol: String,\n");
    generated_code.push_str("    pub meta_var_char: Option<char>,\n");
    generated_code.push_str("    pub expando_char: Option<char>,\n");
    generated_code.push_str("    pub extensions: Vec<String>,\n");
    generated_code.push_str("}\n\n");

    generated_code.push_str(
        "static EMBEDDED_LIBS: OnceLock<HashMap<String, EmbeddedLib>> = OnceLock::new();\n\n",
    );
    generated_code
        .push_str("pub fn get_embedded_libs() -> &'static HashMap<String, EmbeddedLib> {\n");
    generated_code.push_str("    EMBEDDED_LIBS.get_or_init(|| {\n");
    generated_code.push_str("        let mut map = HashMap::new();\n");

    for (lang_name, lang_config) in config.iter() {
        let obj = lang_config
            .as_object()
            .expect("Language config must be an object");

        let lib_path = if let Some(lib_path_value) = obj.get("libraryPath") {
            if lib_path_value.is_string() {
                lib_path_value.as_str().unwrap().to_string()
            } else if lib_path_value.is_object() {
                // Platform-specific paths
                let platform_map = lib_path_value.as_object().unwrap();
                let target = env::var("TARGET").unwrap();

                if let Some(path) = platform_map.get(&target) {
                    path.as_str().expect("Path must be a string").to_string()
                } else {
                    eprintln!(
                        "No library path for target {} in language {}",
                        target, lang_name
                    );
                    continue;
                }
            } else {
                eprintln!("Invalid libraryPath format for language {}", lang_name);
                continue;
            }
        } else {
            eprintln!("No libraryPath found for language {}", lang_name);
            continue;
        };

        let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
        let absolute_lib_path = PathBuf::from(&manifest_dir)
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .join(&lib_path);

        if !absolute_lib_path.exists() {
            eprintln!("Library not found at path: {:?}", absolute_lib_path);
            continue;
        }

        let var_name = lang_name
            .replace('-', "_")
            .replace('+', "plus")
            .to_uppercase();
        let bytes_var = format!("{}_BYTES", var_name);

        generated_code.push_str(&format!(
            "        const {}: &[u8] = include_bytes!(\"{}\");\n",
            bytes_var,
            absolute_lib_path.to_string_lossy().replace('\\', "\\\\")
        ));

        let symbol = obj
            .get("languageSymbol")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string())
            .unwrap_or_else(|| format!("tree_sitter_{}", lang_name));

        let meta_var_char = obj
            .get("metaVarChar")
            .and_then(|v| v.as_str())
            .and_then(|s| s.chars().next())
            .map(|c| format!("Some('{}')", c))
            .unwrap_or_else(|| "None".to_string());

        let expando_char = obj
            .get("expandoChar")
            .and_then(|v| v.as_str())
            .and_then(|s| s.chars().next())
            .map(|c| format!("Some('{}')", c))
            .unwrap_or_else(|| "None".to_string());

        let extensions = obj
            .get("extensions")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str())
                    .map(|s| format!("\"{}\".to_string()", s))
                    .collect::<Vec<_>>()
                    .join(", ")
            })
            .unwrap_or_default();

        generated_code.push_str(&format!(
            "        map.insert(\"{}\".to_string(), EmbeddedLib {{\n",
            lang_name
        ));
        generated_code.push_str(&format!("            data: {},\n", bytes_var));
        generated_code.push_str(&format!(
            "            symbol: \"{}\".to_string(),\n",
            symbol
        ));
        generated_code.push_str(&format!("            meta_var_char: {},\n", meta_var_char));
        generated_code.push_str(&format!("            expando_char: {},\n", expando_char));
        generated_code.push_str(&format!("            extensions: vec![{}],\n", extensions));
        generated_code.push_str("        });\n");

        println!("cargo:rerun-if-changed={}", absolute_lib_path.display());
    }

    generated_code.push_str("        map\n");
    generated_code.push_str("    })\n");
    generated_code.push_str("}\n");

    println!("generated_code: {}", generated_code);
    fs::write(&dest_path, generated_code).expect("Failed to write generated code");

    println!("cargo:rerun-if-env-changed=PRE_REGISTER_JSON_CONFIG");
}
