# yaml-language-server: $schema=https://raw.githubusercontent.com/codemod/codemod/refs/heads/main/schemas/workflow.json

version: "1"

nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    steps:
      - name: "Scan {language} files and apply fixes"
        js-ast-grep:
          js_file: scripts/codemod.ts
          language: "{language}"
